### ISSUE TITLE
Using the official Nvidia API for the games list?

### ISSUE THREAD

**Issue by arcataroger** [aducad/cloud-game-lister#10]
Hi there,

Thank you for this useful extension! I've been using it for a few years now.

Recently, I started having trouble with the games list either not showing the latest supported games, or sometimes not loading at all. I was wondering if this might be an occasional issue with the API used (gameplus), at https://github.com/aducad/cloud-game-lister/blob/master/src/background/index.js#L13 ?

@JulyIghor documented the official API's graphQL on a blog post here: https://ighor.medium.com/i-unlocked-nvidia-geforce-now-and-stumbled-upon-pirates-dc48a3f8ff7

And from that, there is a simple script that can get all the app IDs directly from Nvidia: https://github.com/arcataroger/show-geforce-on-steam/blob/dev/getSteamIds.js

What gets you is a simple array of steam IDs that can be directly included in the extension, if desired, at least as a default fallback in case of API glitches: https://github.com/arcataroger/show-geforce-on-steam/blob/dev/data.js

Would this be useful at all? Is there a reason to prefer the Gameplus API over the official Nvidia one?

I can make a PR for this if that helps, but just wanted to discuss it here first. Thanks!

**Comment by demiryasinoruc** [comment]
Hi @arcataroger,

First of all, thank you for the information and sorry for the late response.

When I first developed the extension, I was using the endpoint on the GFN official website, but later they made a change and since I did not have much research time, I started using the endpoint on the GamePlus website in Turkey.

I can't spare time for the plugin right now because my daily job takes up a lot of my time. Also, the extension is currently working with MV2 and I need to switch it to MV3. If you make a report about the existing problem, I will be happy to accept it. Otherwise, if I can spare time soon, I will make the necessary update with the new version. I plan to do

**Comment by arcataroger** [comment]
@demiryasinoruc No problem at all, and thanks for the response! We're all just volunteers in our spare time :) I'll try to make a PR for it if I can, but it might take me a few weeks too. No rush in either case. Thank you, and good luck with the job!

**Comment by demiryasinoruc** [comment]
Thank you :)
