### ISSUE TITLE
Incompatible with Augmented Steam

### ISSUE THREAD

**Issue by VictorVow** [aducad/cloud-game-lister#6]
I use another browser extension called [Augmented Steam](https://chrome.google.com/webstore/detail/augmented-steam/dnhpnfgdlenaccegplpojghhmaamnnfp) for finding deals and other useful info on other Steam games, however I noticed on the Wishlist page if I have Cloud Game Lister active then it'll mess up the ordering, leaving gaps inbetween games and break drag-and-drop.

**Comment by emresandikci** [comment]
First of all, we don't need to be compatible with other extensions. Because most of the extensions manipulate page content to show you some new content, because of that you can get some issues with other extensions. It can happen for all extensions.

So, as a solution, for now, you can switch off the extensions when you don't need them. It's a concern for all of the extensions not just for CGL ( Cloud Game Lister). 

You can use this extension to manage all extensions on/off status from one place => [Extensity](https://chrome.google.com/webstore/detail/extensity/jjmflmamggggndanpgfnpelongoepncg). 

But if you have some solution you can create a PR for the issue we can review and merge it. or if we can find some solution we can release new version.

**Comment by VictorVow** [comment]
You don't have to of course, but Augmented Steam is an extremely popular and useful extension. I'm raising this just to let you know because I expect many users who would download your extension also already have Augmented Steam, and if they're like me they'll just uninstall CGL until it gains compatibility.

**Comment by demiryasinoruc** [comment]
Hi,

i fixed the bug in version 1.3.6 (under review in chrome web store)

PS: bug was not related with any other extension

**Comment by demiryasinoruc** [comment]
> You don't have to of course, but Augmented Steam is an extremely popular and useful extension. I'm raising this just to let you know because I expect many users who would download your extension also already have Augmented Steam, and if they're like me they'll just uninstall CGL until it gains compatibility.

Hi,

i fixed the bug in version 1.3.6 (under review in chrome web store)

PS: bug was not related with any other extensions

**Comment by emresandikci** [comment]
@Victor239 after release is approved, you can test it and give us feedback and we can close this issue.

**Comment by VictorVow** [comment]
Sure, will do.

**Comment by VictorVow** [comment]
Looks fixed to me, thanks!

**Comment by emresandikci** [comment]
> Looks fixed to me, thanks!

You are welcome, we can close the issue.
